name: Build, test and push to the Client Library

on:
  workflow_dispatch:
      inputs:
        version_major:
          description: 'OpenCloudOS major version'
          required: true
          default: '23'

        type_default:
          description: 'default'
          required: true
          type: boolean
          default: true

        type_minimal:
          description: 'minimal'
          required: true
          type: boolean
          default: true

env:
  # Latest version
  version_latest: 23

  # Platforms list: linux/loong64
  platforms: 'linux/loong64'

  # Registries list:
  registries: 'ghcr.io/loong64'

jobs:
  build-test-push:
    name: Deploy ${{ inputs.version_major }} ${{ matrix.image_types }} images
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        # Set image types matrix based on boolean inputs.type_* with true value
        image_types: ${{ fromJSON(format('["{0}", "{1}"]', ( inputs.type_default && 'default' ), ( inputs.type_minimal && 'minimal' ))) }}
        exclude:
          - image_types: 'false'

    steps:

      -
        name: Prepare OpenCloudOS Minor version number
        run: |
          case ${{ inputs.version_major }} in
            23)
              version_minor= ;;
            *)
              echo "OpenCloudOS ${{ inputs.version_major }} is not supported!" && false
          esac
          echo "version_minor=${version_minor}" >> $GITHUB_ENV

          # [Debug]
          echo "version_minor=${version_minor}"

      -
        name: Prepare date stamp
        id: date_stamp
        run: |
          # date stamp
          date_stamp=$(date -u '+%Y%m%d')
          echo "date_stamp=${date_stamp}" >> $GITHUB_ENV
          echo "date_stamp=${date_stamp}" >> "$GITHUB_OUTPUT"
          [ -z "$date_stamp-x" ] && false

          # [Debug]
          echo "date_stamp=${date_stamp}"

      -
        name: Generate list of images to use as base name for tags
        run: |
          # list of registries to push to
          REGISTRIES="${{ env.registries }}"

          IMAGE_NAMES=
          # generate image names in format $REGISTRY/opencloudos
          # image names are used by docker/metadata-action to set 'images'
          for REGISTRY in ${REGISTRIES//,/ }; do
            # 'default' images goes to $REGISTRY/opencloudos
            IMAGE_NAME="$REGISTRY/opencloudos"
            IMAGE_NAMES="${IMAGE_NAMES} ${IMAGE_NAME}"
            unset IMAGE_NAME
          done

          # remove space at the beginning of string
          IMAGE_NAMES=${IMAGE_NAMES# }
          # separate with comma instead of space and export to the action
          echo "IMAGE_NAMES=${IMAGE_NAMES// /,}" >> $GITHUB_ENV

          # [Debug]
          echo $IMAGE_NAMES

      -
        name: Enable containerd image store on Docker Engine
        run: |
          # JQ file to switch into containerd image store
          cat << EOF > containerd-snapshotter.jq
          .features |= . + { "containerd-snapshotter": true }
          EOF
          sudo sh -c 'jq -n -f containerd-snapshotter.jq > /etc/docker/daemon.json'
          sudo systemctl restart docker
          docker info -f '{{ .DriverStatus }}'

      -
        name: Checkout ${{ github.repository }}, branch 'main'
        uses: actions/checkout@v4

      -
        name: Checkout ${{ github.repository }}, branch '${{ inputs.version_major }}', path '${{ inputs.version_major }}'
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.version_major }}
          path: ${{ inputs.version_major }}

      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      -
        name: Set up QEMU
        run: docker run --rm --privileged ghcr.io/loong64/qemu-user-static --reset -p yes

      -
        name: Login to Ghcr.io
        if: contains(env.registries, 'ghcr.io')
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      -
        name: Generate tags and prepare metadata to build and push
        id: meta
        uses: docker/metadata-action@v5
        with:
          # list of Docker images to use as base names for tags
          images: ${{ env.IMAGE_NAMES }}

          # list of tags
          tags: |
            # Default image tags
            type=raw,value=latest,enable=${{ matrix.image_types == 'default' }}
            type=raw,value=${{ inputs.version_major }},enable=${{ matrix.image_types == 'default' }}
            type=raw,value=${{ inputs.version_major }}${{ env.version_minor }},enable=${{ matrix.image_types == 'default' }}
            type=raw,value=${{ inputs.version_major }}${{ env.version_minor }}-${{ env.date_stamp }},enable=${{ matrix.image_types == 'default' }}
            # Minimal image tags
            type=raw,value=${{ matrix.image_types }},enable=${{ matrix.image_types == 'minimal' }}
            type=raw,value=${{ inputs.version_major }}-${{ matrix.image_types }},enable=${{ matrix.image_types == 'minimal' }}
            type=raw,value=${{ inputs.version_major }}${{ env.version_minor }}-${{ matrix.image_types }},enable=${{ matrix.image_types == 'minimal' }}
            type=raw,value=${{ inputs.version_major }}${{ env.version_minor }}-${{ matrix.image_types }}-${{ env.date_stamp }},enable=${{ matrix.image_types == 'minimal' }}

      -
        name: Build images
        id: build-images
        uses: docker/build-push-action@v5
        with:
          provenance: false
          context: "{{defaultContext}}:Containerfiles/${{ inputs.version_major }}"
          file: ./Containerfile.${{ matrix.image_types }}
          platforms: ${{ env.platforms }}
          push: false
          load: true
          tags: ${{ steps.meta.outputs.tags }}

      -
        name: Test images
        id: test-images
        run: |
          # [Test]
          platforms="${{ env.platforms }}"
          for platform in ${platforms//,/ }; do
            echo "Testing OpenCloudOS ${{ inputs.version_major }} ${{ matrix.image_types }} for ${platform} image:"

            docker run --platform=${platform} ${{ steps.build-images.outputs.digest }} /bin/bash -c " \
            uname -m \
            && cat /etc/opencloudos-release \
            && ( test "${{ matrix.image_types }}" != "micro" && rpm -q gpg-pubkey) || true "
          done

      -
        name: Push images to Client Library
        id: push-images
        uses: docker/build-push-action@v5
        with:
          provenance: false
          context: "{{defaultContext}}:Containerfiles/${{ inputs.version_major }}"
          file: ./Containerfile.${{ matrix.image_types }}
          platforms: ${{ env.platforms }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}

      -
        name: Extract RootFS (default and minimal only)
        id: extract-rootfs
        # 'default' or 'minimal' images only go to Docker Official Library
        if: matrix.image_types == 'default' || matrix.image_types == 'minimal'
        run: |
          # [RootFS]

          # File name for RootFS file (packed with tag + Xz)
          name=opencloudos-${{ inputs.version_major }}-${{ matrix.image_types }}
          pwd=$( pwd )
          path=${pwd}/${name}
          opencloudos_release='bash'

          # The "tar file" for 'docker save' to write to
          tar_name=${pwd}/${name}.tar

          mkdir ${path}
          cd ${path}

          # Produce a tarred repository and save it to the "tar file".
          docker save ${{ steps.build-images.outputs.digest }} -o ${tar_name}

          # Extract the "tar file"
          tar xf ${tar_name}
          cd blobs/sha256

          # The "temporary Dockerfile" to build image based on RootFS
          cat <<EOF > Dockerfile
          FROM scratch
          ADD rootfs.tar.gz /
          CMD ["/bin/bash"]
          EOF

          # Loop blobs to find all zipped files that are RootFS for a particular architecture
          for file in `find . -type f`; do
            if file --brief ${file} | grep -i gzip >/dev/null; then
              # Make a copy of "taken RootFS"
              cp -av ${file} rootfs.tar.gz

              # Build an image from the "temporary Dockerfile"
              docker build -t rootfs .

              # Run the image and query opencloudos-release package's architecture
              arch=$( docker run --rm rootfs /bin/bash -c "rpm -q --qf=%{ARCH} ${opencloudos_release}" )

              # Map found architecture to the corresponding platform
              platform=
              docker rmi rootfs
              case ${arch} in
                loongarch64)
                  platform=loong64;;
                *)
                  echo "The '$arch' is incorrect or failed to determine architecture." && false;;
              esac

              # Delete copy of the "taken RootFS"
              rm -f rootfs.tar.gz

              # Copy the "taken RootFS" into corresponded .tar.xz
              cp -av ${file} ${name}-${platform}.tar.gz
              zcat ${name}-${platform}.tar.gz | xz -9 -e -T0 > ${pwd}/${{ inputs.version_major }}/${{ matrix.image_types }}/${platform}/${name}-${platform}.tar.xz

            fi
          done

          # Clean up
          rm -rf ${path}

          echo "[Debug]"
          ls -1 ${pwd}/${{ inputs.version_major }}/${{ matrix.image_types }}/*/*.tar.xz

      # Change date stamp in '${version_major}/${image_types}/${arch}/Dockerfile'
      -
        name: Change date stamp in Dockerfile (default and minimal only)
        # 'default' or 'minimal' images only go to Docker Official Library
        if: matrix.image_types == 'default' || matrix.image_types == 'minimal'
        run: |
          # [Dockerfile]

          platforms="${{ env.platforms }}"
          for platform in ${platforms//,/ }; do
            arch=${platform#linux/}
            arch=${arch/\//_}
            dockerfile=${{ inputs.version_major }}/${{ matrix.image_types }}/${arch}/Dockerfile

            case ${{ matrix.image_types }} in
              default)
                tags="${{ inputs.version_major }}${{ env.version_minor }}, ${{ inputs.version_major }}${{ env.version_minor }}-${{ env.date_stamp }}"
                [ "${{ inputs.version_major }}" = "${{ env.version_latest }}" ] && tags="latest, ${tags}" ;;
              minimal)
                tags="${{ inputs.version_major }}${{ env.version_minor }}-${{ matrix.image_types }}, ${{ inputs.version_major }}${{ env.version_minor }}-${{ matrix.image_types }}-${{ env.date_stamp }}"
                [ "${{ inputs.version_major }}" = "${{ env.version_latest }}" ] && tags="minimal, ${tags}" ;;
              *)
            esac

            # Tags: 23, 23-20241216
            sed -i "/^\([[:space:]]*#[[:space:]]*Tags: \).*/s//\1${tags}/" ${dockerfile}

            echo "[Debug] ${dockerfile}"
            cat ${dockerfile}
          done

      -
        name: "Prepare time stamp"
        id: time_stamp
        run: |
          # time stamp
          time_stamp=$(date -u '+%H:%M:%S')
          echo "time_stamp=${time_stamp}" >> $GITHUB_ENV
          echo "time_stamp=${time_stamp}" >> "$GITHUB_OUTPUT"
          [ -z "$time_stamp-x" ] && false

          # [Debug]
          echo "time_stamp=${time_stamp}"

      # Commit '${version_major}/${image_types}/${arch}/*'
      -
        name: "Commit and push ${{ matrix.image_types }}/*/* Dockerfile and RootFS (branch ${{ inputs.version_major }})"
        # 'default' or 'minimal' images only and 'Push to production' is checked
        if: ( matrix.image_types == 'default' || matrix.image_types == 'minimal' )
        uses: EndBug/add-and-commit@v9
        with:
          default_author: user_info
          new_branch: ${{ inputs.version_major }}
          cwd: ${{ inputs.version_major }}
          pull: '--rebase --autostash'
          message: "OpenCloudOS ${{ inputs.version_major }} ${{ matrix.image_types }} - ${{ env.date_stamp }} ${{ env.time_stamp }} (generated on ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})."
          push: true

    outputs:
      date_stamp: ${{ steps.date_stamp.outputs.date_stamp }}
      time_stamp: ${{ steps.time_stamp.outputs.time_stamp }}

  optimize-repo-size:
    # 'default' or 'minimal' images only and 'Push to production' is checked
    if: ( inputs.type_default || inputs.type_minimal )
    name: Optimize size of repository
    runs-on: ubuntu-24.04
    needs:
      - build-test-push
    steps:

      -
        name: Checkout ${{ github.repository }}, branch '${{ inputs.version_major }}', path '${{ inputs.version_major }}'
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.version_major }}
          path: ${{ inputs.version_major }}

      -
        name: Optimize size of branch the '${{ inputs.version_major }}'
        run: |
          date_stamp=${{ needs.build-test-push.outputs.date_stamp }}
          cd ${{ inputs.version_major }}

          echo "Prepare new branch 'tmp' based on ${{ inputs.version_major }}"
          git checkout -b tmp

          echo "Delete local branch '${{ inputs.version_major }}'"
          git branch -D ${{ inputs.version_major }}

          echo "Preserve resent data"
          mkdir ../tmp-${date_stamp}

          mv ./default ../tmp-${date_stamp}/
          mv ./minimal ../tmp-${date_stamp}/

          echo "Crete orphan branch '${{ inputs.version_major }}'"
          git checkout --orphan ${{ inputs.version_major }}

          echo "Clean up"
          git rm --cached -r .
          rm -rf ./default
          rm -rf ./minimal

          echo "Restore resent data"
          mv ../tmp-${date_stamp}/default ./
          mv ../tmp-${date_stamp}/minimal ./

          echo "[Debug]"
          git status

      -
        name: Commit and push ${{ github.repository }}, branch '${{ inputs.version_major }}'
        uses: EndBug/add-and-commit@v9
        with:
          default_author: user_info
          message: "Update OpenCloudOS ${{ inputs.version_major }} - ${{ needs.build-test-push.outputs.date_stamp }} ${{ needs.build-test-push.outputs.time_stamp }} (generated on ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})."
          push: '--force --set-upstream origin ${{ inputs.version_major }}'
          cwd: ${{ inputs.version_major }}
